module
-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gen_lib_entry]: function definitions
public import Aeneas
public import GenLibEntry.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace gen_lib_entry

/-- [gen_lib_entry::f]:
    Source: 'tests/src/gen_lib_entry.rs', lines 8:0-10:1
    Visibility: public -/
def f (x : Std.U32) : Result Std.U32 := do
  x + 1#u32

/-- [gen_lib_entry::g]:
    Source: 'tests/src/gen_lib_entry.rs', lines 12:0-14:1
    Visibility: public -/
def g (x : Std.U32) : Result Std.U32 := do
  let i ← f x
  i + 1#u32

end gen_lib_entry
