import Aeneas.Std.Scalar.Ops.Add
import Aeneas.Std.Scalar.Ops.Add_aux
import Aeneas.Std.Scalar.Ops.Div
import Aeneas.Std.Scalar.Ops.Div_aux
import Aeneas.Std.Scalar.Ops.Mul
import Aeneas.Std.Scalar.Ops.Mul_aux
import Aeneas.Std.Scalar.Ops.Neg
import Aeneas.Std.Scalar.Ops.Rem
import Aeneas.Std.Scalar.Ops.Rem_aux
import Aeneas.Std.Scalar.Ops.Sub
import Aeneas.Std.Scalar.Ops.Sub_aux
